# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: NI Diagram SDK Concepts and Documentation
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
    We are quite a way from being finished with this public documentation, so expect ugly pages, broken links and incomplete information to be the norm for a while. Furthermore, the documentation I'm starting with is quite dated. We'll be updating it to reflect the current state of the product, but it's going to be easier to transfer our current internal documentation as is and then update it after the framework is mostly complete. When this is actually ready for consumption, we'll likely pull it in to the official NI repo. Until that point, don't trust it to be correct (or even helpful).


baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  ChrisStrykesAgain

collections:
  pages:
    output: true

# Build settings
markdown: kramdown
theme: minima
highlighter: pygment
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
